// Code generated by cmd/generate/main.go. DO NOT EDIT.

package protocol

const (

	// Debug Packets
	PacketTypeDebugHello PacketType = 0x90 // Debug: Hello
	PacketTypeDebugAny   PacketType = 0x91 // Debug: Any

	// Non Payload Packets
	PacketTypeNone                  PacketType = 0x00
	PacketTypeClientNeedsDisconnect PacketType = 0x01 // Client needs to disconnect

	// Payload Packets
	PacketTypeAck PacketType = 0x32 // Ack

)

var (
	PacketTypeMap = []PacketTypeMapping{
		{PacketType: PacketTypeNone, String: "None"},
		{PacketType: PacketTypeClientNeedsDisconnect, String: "ClientNeedsDisconnect"},
		{PacketType: PacketTypeDebugHello, String: "DebugHello"},
		{PacketType: PacketTypeDebugAny, String: "DebugAny"},
		{PacketType: PacketTypeAck, String: "Ack"},
	}

	PacketTypeMapType = func() map[PacketType]string {
		m := make(map[PacketType]string)
		for _, mapping := range PacketTypeMap {
			m[mapping.PacketType] = mapping.String
		}
		return m
	}()
)
